name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    environment: Deployment
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Installing dependencies
        run: npm install
      # - name: Publish to NPM
      #   uses: mikeal/merge-release@v4.0.7
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GH_ACCESS_TOKEN}}
      #     NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - name: Publish manually
        run: NPM_CONFIG_TOKEN=${{secrest.NPM_AITH_TOKEN}}
